ntp:
  servers:
  - ip: 192.168.78.148

bgp:
  id: '65001'
  rid: 1.1.1.3
  neighbors:
  - id: 1.1.1.1
    as: '65001'
    loopsource: '0'
  - id: 1.1.1.2
    as: '65001'
    loopsource: '0'
  - id: 1.1.1.4
    as: '65001'
    loopsource: '0'
  ipv4_unicast_family:
  - neighborid: 1.1.1.1
  - neighborid: 1.1.1.2
  - neighborid: 1.1.1.4
  networks:
  - number: 30.30.30.0
    mask: 255.255.255.0

ospf:
  id: '1'
  rid: 1.1.1.3
  networks:
  - ip: 1.1.1.3
    mask: 0.0.0.0
    area: '0'

ip:
  domain: cisco.com
  tftp_source_gi_int: '1'
  source_interface: GigabitEthernet1
  vrf:
  - name: MGMT
    description: OOB Management

interfaces:
  GigEthernet:
  - name: '1'
    description: OOB Management
    vrf: MGMT
    ip: 192.168.78.23
    mask: 255.255.255.0
  - name: '2'
    description: Link Core3-to-Core1
    unnumbered: Loopback0
    ospf_network: point-to-point
  - name: '3'
    description: Link Core3-to-Core4
    unnumbered: Loopback0
    ospf_network: point-to-point
  - name: '4'
    shutdown: 'True'
  - name: '5'
    shutdown: 'True'
  Loopback:
  - name: '0'
    description: Core3-id
    ip: 1.1.1.3
    mask: 255.255.255.255
  - name: '30'
    description: BGP Advertised Loopback
    ip: 30.30.30.1
    mask: 255.255.255.0

crypto:
  self_signed_certificate: '3899247252'

